---
title: "Inequalities in College Financial Outcomes"
subtitle: "Data Visualization Final Project"
description: |
  Jerry Shu | March 2025
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 1. Introduction
To many in America, obtaining a secondary school diploma is viewed as a way to improve one's career prospects. In fact, many believe that higher education provides an opportunity to increase one's earning potential. However, the outcome of a college education cannot be described as equal across all higher education institutions. [While there exists substantial evidence that a college education can improve one's earnings overall](https://www.nyu.edu/about/news-publications/news/2024/march/study-of-5-8-million-americans-finds-that-a-college-degree-yield.html), there also exist deep inequalities in the ways colleges improve the financial outcomes for those who attend. 

This project aims to visualize some of these inequalities. The motivation lies in the following two research questions:

1. How do American four-year undergraduate colleges provide financial opportunities to their students?
2. With regards to such opportunities, what disparities exist among different institutions and academic majors? 

The goal of this project is to use the College Scorecard dataset to visualize answers to the questions above. By aggregating via insitutional characteristics and fields of study, we can 
observe some of the inequalities that exist within the college system.

# 2. Data and Methods 

## Datasets
This project utilizes the following datasets:

1. [College Scorecard Dataset](https://collegescorecard.ed.gov/data): This dataset is provided by the U.S. Department of Education, containing information on all degree-granting higher education institutions in the U.S. Data is available at the institution and field-of-study level for each year from 1996-97 to 2022-23 across a variety of factors, including costs, completion, financial aid, debt, repayment, and earnings. The dataset was filtered for four-year colleges only; this was to facilitate equitable analysis across colleges. As such, this analysis only applies to undergraduate programs. Unless otherwise noted, the data for this project was sourced from the 2022-23 school year, which was the most recent cohort of data available at the time of my research. Additionally, the College Scorecard data reflects students who received federal financial aid. Consequently, the earnings data may not fully represent students who did not utilize federal aid programs. 
2. [CIP Codes Dataset](https://nces.ed.gov/ipeds/cipcode/resources.aspx?y=55): This dataset from the National Center for Education Statistics contains the CIP codes and their corresponding fields of study. 'CIP' stands for "Classification of Instructional Programs." 
3. [US News Top 150 Rankings](https://andyreiter.com/datasets/): This dataset is provided by Professor Andrew G. Reiter at Mount Holyoke College, and it contains historical data on the top 150 university rankings from US News and World Report.

## Methods
* **Webpage**: The webpage that contains this report was created using [Distill in RMarkdown](https://rstudio.github.io/distill/).
* **Visualizations**: The visualizations in this report were rendered using Altair. Additional annotations were added via Figma.
* **Analysis**: The analysis for this report was done in a literate programming style in an iPython notebook.
* **Regression**: I used an `XGBoost` regression model for feature selection and a K-Means clustering algorithm for clustering. See the notebook for an in-depth justification of the parameters used.

# 3. Results and Analysis

## ROI by Type of Institutional Funding

First, I wanted to explore broadly if there were obvious differences in ROI between the types of school ownership: public, private non-profit, and private for-profit. The x-axis measures the average cost of attendance, while the y-axis measures the median earnings for graduates 10 years after enrolling. Due to data limitations, the only available years for these data were 2011, 2012, 2013, 2014, and 2020. Plotting over the years, a consistent pattern emerges: it appears that private, non-profit institutions have on average higher costs of attendance and are grouped further to the right on the chart, compared to public institutions. We expect to see this, as [public institutions generally have lower costs due to government funding](https://soeonline.american.edu/blog/private-vs-public-institutions/#:~:text=Due%20to%20government%20funding%2C%20public,often%20have%20higher%20tuition%20costs.). Furthermore, there is a slight positive correlation between earnings and cost overall.

*The following visualization is interactive. Click on the `Year` tab to switch between different years.*

<!-- Interactive ROI Scatterplot by Year -->
<div class="figure">
  <iframe src="figures/interactive_scatter_roi_years.html" width="100%" height="420" style="border:none;"></iframe>
  <p class="caption">Figure: ROI by school ownership over the years</p>
</div>

Grouping by institution type may be too broad for deep analysis, however, as the definition for what constitutes a private non-profit institution encompasses a wide range of institution types. For instance, private non-profit institutions could be any of the following:

* **Large research universities** with a wide range of academic majors and large endowments
* **Religiously affiliated institutions** with a narrow selection of majors relating to theology
* **Specialized or niche colleges** such as music conservatories

It follows that more specific comparisons of the data can facilitate deeper analysis.

## ROI by School Ranking

According to many accounts, a school’s perceived 'prestige' serves as a significant factor in attracting students who aim to maximize their future earnings potential. The following visualization returns to the scatterplot exploring cost of attendance versus median earnings 10 years post-enrollment, but asks a fundamentally different question: does being in the top 150 of schools ranked by the popular publication, US News & World Report, give students an advantage in ROI over other schools?

<!--- Top 150 vs. Others --->
<div class="figure">
  <iframe src="figures/top_150_vs_others_roi.svg" width="100%" height="400" style="border:none;"></iframe>
  <p class="caption">Figure: ROI for Top 150 vs. all other schools</p>
</div>

Inspecting the scatterplot, we find that the median earnings for the top 150 are on average towards the higher end of the scale; they appear to occupy the top right parts of the two clusters mentioned previously, those being public and private non-profit institutions.

## ROI by Clustering Analysis

The analysis above demonstrates significant differences in ROI with regards to the type of institution and its prestige. However, there are a multitude of other factors in the school and student profile that may influence a school's position on the ROI scatterplot. To investigate further, I used a regression model to determine the most important features that determine ROI (defined as median earnings / average cost), and then clustered with K-means to visualize the groups between these schools. This can assist in determing how schools can be categorized based on their ROI. As a result of the regression analysis, I used the following variables from the College Scorecard dataset for the clustering algorithm:

* Percent of all undergraduate students receiving a federal student loan
* Percentage of degrees awarded in Transportation And Materials Moving, Visual And Performing Arts, Social Sciences, Parks, Recreation, Leisure, And Fitness Studies, Engineering
* Share of undergraduate, degree-/certificate-seeking students who are part-time
* Percent of students whose parents' highest educational level is high school
* Share of dependent students
* Share of students who received a federal loan while in school
* Median family income
* Percentage of undergraduates aged 25 and above
* First-time, full-time student retention rate at four-year institutions
* Percent of student body that is Hispanic
* Percent of student body that is female-identifying
* State Postcode
* Highest degree offered
* Institution type (e.g., private non-profit)
* [Carnegie Classification](https://carnegieclassifications.acenet.edu) (basic classification of schools)

I chose the top 30 variables from the regression analysis for the clustering algorithm, and chose to use 8 clusters, as I found that was the optimal amount of clusters (see notebook for details). The following visualization represents those clusters in the ROI scaterplot:

*The following visualization is interactive. Click on the legend to filter for different clusters. Holding `shift` allows for multi-selection. Click anywhere on the chart to reset. Hovering over any data point brings up its tooltip.*

<!-- Interactive ROI Scatterplot by Clustering -->
<div class="figure">
  <iframe src="figures/interactive_scatter_roi_clustering.html" width="100%" height="600" style="border:none;"></iframe>
  <p class="caption">Figure: ROI by Clustering</p>
</div>

### Overall Cluster Observations

The following represents my interpretation of the clustering phenomena observed in the scatterplot. For the purposes of this analysis, I produced a series of visualizations that show each variable in the clustering algorithm and its distribution. The full list of visualizations can be found in the computational notebook. 

Note that for some of the visualizations, I refer to two variables: the majority state of that cluster, and the cluster's ROI. For the sake of concision, I've included these two visualizations here at the top and link back to these visualizations. Hover over the graph to see the counts/ROI for each state.

<!--- State --->
<div id="fig:cluster_avgs_state" class="figure">
  <iframe src="figures/cluster_avgs_state.html" width="100%" height="380" style="border:none;"></iframe>
  <p class="caption">Figure: State Count by Cluster</p>
</div>

<!--- ROI --->
<div id = "fig:cluster_avgs_roi" class="figure">
  <iframe src="figures/cluster_avgs_roi.html" width="100%" height="380" style="border:none;"></iframe>
  <p class="caption">Figure: ROI by Cluster</p>
</div>


### Cluster 0: North Carolina schools
The points in this cluster seem rather dispersed, especially with Duke University and Southern Methodist University as extreme outliers. Examining the distributions, it appears that these schools have more than twice the average percentage of degrees awarded in Parks, Recreation, Leisure, And Fitness Studies than other schools, and almost all of these schools are located in North Carolina ([see Figure](#fig:cluster_avgs_state)). This cluster remains hard to interpret.

<!--- Parks & Rec --->
<div class="figure">
  <iframe src="figures/cluster_avgs_parks.html" width="100%" height="380" style="border:none;"></iframe>
  <p class="caption">Figure: Avg. Parks & Rec Percentages by Cluster</p>
</div>

### Cluster 1: Hispanic Texas schools

The schools in this cluster are also rather dispersed, and contain a mix of public and private non-profit schools. However, a defining characteristic is that this cluster has a high average percentage of Hispanic students, and a majority of these schools are in Texas ([see Figure](#fig:cluster_avgs_state)).

<!--- Hispanic --->
<div id="fig:cluster_avgs_hisp" class="figure">
  <iframe src="figures/cluster_avgs_hisp.html" width="100%" height="380" style="border:none;"></iframe>
  <p class="caption">Figure: Avg. Hispanic Percentages by Cluster</p>
</div>

### Cluster 2: High earnings, wealthy family background schools

The schools in this cluster contain a mixture of high earnings, public and private non-profit schools, with a large range in cost of attendance. Institutions in this cluster have an average median family income far higher than other clusters, and there is also the highest average concentration of social sciences majors in this cluster.

<!--- Median Family Income --->
<div id="fig:cluster_avgs_MD_FAMINC" class="figure">
  <iframe src="figures/cluster_avgs_MD_FAMINC.html" width="100%" height="380" style="border:none;"></iframe>
  <p class="caption">Figure: Avg. Median Family Income by Cluster</p>
</div>

### Cluster 3: Public schools with a focus on engineering and high ROI

Schools in this cluster are predominantly public institutions with a high proportion of engineering majors, but there are also two outliers in Stanford and Yale University. This cluster has the highest ROI of any cluster ([see Figure](#fig:cluster_avgs_roi)).

<!--- Engineering --->
<div class="figure">
  <iframe src="figures/cluster_avgs_engineering.html" width="100%" height="380" style="border:none;"></iframe>
  <p class="caption">Figure:  Avg. Engineering Percentages by Cluster</p>
</div>

### Cluster 4: Private schools, low ROI, with a focus on visual and performing arts

This cluster has the highest average proportion of visual and performing arts majors and are predominantly private non-profit. This is explained by the inclusion of schools such as the American Musical and Dramatic Academy and the New York Film Academy. This cluster also has the second-highest average median family income ([see Figure](#fig:cluster_avgs_MD_FAMINC)), but it also has the lowest ROI ([see Figure](#fig:cluster_avgs_roi)).

<!--- Visual and Performing Arts --->
<div class="figure">
  <iframe src="figures/cluster_avgs_viz_arts.html" width="100%" height="380" style="border:none;"></iframe>
  <p class="caption">Figure:  Avg. Visual and Performing Arts Percentages by Cluster</p>
</div>

### Cluster 5: Low-cost, low-federal loans, predominantly Hispanic schools

This cluster has the lowest average proportion of students who have taken out a federal loan; this is an interesting insight given that these schools are clustered at the bottom left of the scatterplot, with low cost *and* earnings. This cluster has the highest average proportion of Hispanic students, at nearly 100%, ([see Figure](#fig:cluster_avgs_hisp)) which makes sense as many of these universities are located in Puerto Rico ([see Figure](#fig:cluster_avgs_state)).

<!--- Percentage Federal Loan --->
<div class="figure">
  <iframe src="figures/cluster_avgs_PCTFLOAN.html" width="100%" height="380" style="border:none;"></iframe>
  <p class="caption">Figure: Avg. Federal Loan Percentages by Cluster</p>
</div>

### Cluster 6: Washington State schools

These schools are on average high in median family income and a somewhat equal mix of private and public, and they are mostly located in Washington State. This cluster seems to have emphasized geography as the unifying factor.

### Cluster 7: Part-time, priavte for-profit schools

The points in this cluster are rather dispersed, with a high average concentration of both students who are part-time and older than 25. Almost all of the private for-profit schools are in this cluster.

<!--- Part Time --->
<div class="figure">
  <iframe src="figures/cluster_avgs_PPTUG_EF.html" width="100%" height="380" style="border:none;"></iframe>
  <p class="caption">Figure: Avg. Part Time Percentages by Cluster</p>
</div>

<!--- Over 25 --->
<div class="figure">
  <iframe src="figures/cluster_avgs_UG25ABV.html" width="100%" height="380" style="border:none;"></iframe>
  <p class="caption">Figure: Avg. Older Than 25 Percentages by Cluster</p>
</div>

Overall, there were several interesting observations:

* The cluster with the highest average engineering concentration also had the highest ROI; the cluster with the highest average visual arts concentration also had the lowest ROI. 
* Some clusters are highly defined by geography, such as Cluster 6, which suggests that regional spatial factors may play a role in ROI.
* The analysis shows a clear divide between private for-profit institutions and all other schools -- they tend to serve part-time students above the age of 25, with an ROI that is towards the middle of the clusters.

## Earnings Trajectory
The analysis above dealt with return on investment at a static point in time: 10 years post-enrollment. The following section will analyze earnings trajectories, looking at how earnings change over time for college graduates.

## Earnings Trajectory Methodology

The College Scorecard dataset also offers median earnings data for multiple cohorts across time. Every institution—and even each major—provides earnings data measured at specific intervals after graduation. These numbers can be used to trace student earnings trajectories.

## Earnings Trajectory by School

First, I'll assess whether a school’s prestige influences students’ average earnings trajectories. One measure of prestige is the previously mentioned top 150 schools, while another, often considered more exclusive, is the Ivy League. Inspecting the chart, we find that the earnings trajectories for the Ivy League and Top 150 schools are consistently above the trajectory for all other schools.

<!--- Earnings Trajectory by Prestige --->
<div class="figure">
  <iframe src="figures/earnings_trajectory_by_prestige.svg" width="100%" height=270 style="border:none;"></iframe>
  <p class="caption">Figure: Earnings Trajectory by Prestige</p>
</div>

## Earnings Trajectory by Field of Study

Another key aspect to examine is the earnings trajectory by field of study; within a single school, earnings potential can differ widely. The visualization below presents the average median earnings over time across all institutions for each field of study. The chart is interactive, and users can explore where the earnings trajectories for each majors lie on the chart.

*The following visualization is interactive. Click on the legend to filter for different majors. Holding `shift` allows for multi-selection. Click anywhere on the chart to reset.*

<!--- Earnings Trajectory by Field of Study --->
<div class="figure">
  <iframe src="figures/interactive_major_earnings_time.html" width="100%" height="740" style="border:none;"></iframe>
  <p class="caption">Figure: Earnings Trajectory by Field of Study</p>
</div>

Fields such as Engineering, Construction Trades, Computer Sciences, and Mathematics and Statistics occupy the higher end of the earnings spectrum, while fields such as Library Science, Theology and Religious Vocations, and Visual and Performing Arts fall on the lower end. [As expected, STEM fields dominate the upper tier](https://www.insidehighered.com/news/students/careers/2023/05/04/measuring-outcomes-income). This trend likely reflects [the strong market demand for entry-level STEM jobs, particularly in the engineering and computer science fields](http://blog.dol.gov/2022/11/04/stem-day-explore-growing-careers). Additionally, this observation aligns with the previous analysis on ROI, as higher ROI was associated with high concentration in Engineering, while lower ROI was associated with a high concentration in the Visual Arts.

However, the available earnings data only covers up to five years, which limits overall applicability. If longer-term data were available in the dataset, it would be worth examining whether earnings in certain fields eventually converge with higher-paying disciplines.

<!--- Earnings Trajectory by Field of Study --->
<div class="figure">
  <iframe src="figures/earnings_trajectory_by_field_of_study.svg" width="100%" height="715" style="border:none;"></iframe>
  <p class="caption">Figure: Earnings Trajectory by Field of Study</p>
</div>

# 4. Discussion and Conclusion

The visualizations reveal that ROI varies significantly by institution type, with private non-profit institutions generally higher in cost and earnings than public ones. The analysis also shows that perceived prestige plays a crucial role in inequal outcomes. The clustering analysis highlighted further distinctions across institutions, including degree concentration, institution type, and geographical characteristics. This polarization suggests that there are a variety of factors that impact student outcomes. Across the different fields of study, earnings trajectories vary, but again the type of institution matters greatly, with higher 'prestige' institutions exhibiting greater earnings throughout the first seven years after graduation. 

While earnings trajectories may vary early on in one's career, some professions -- such as medical professionals -- require additional years of schooling or experience to achieve higher earnings. Furthermore, because the study above was correlative, we cannot definitively conclude that institutional characteristics *cause* the observed differences in ROI; we can only say that the two are associated.

Future analysis could explore a longer earnings horizon with the use of a different dataset. Employing a regression-based analysis could also give further insights as to which factors quantitatively had the largest impact on ROI.

# 5. References

The sources cited throughout have been linked at the point of citation. They are listed here again:

* ["While there exists substantial evidence that a college education can improve one's earnings overall"](https://www.nyu.edu/about/news-publications/news/2024/march/study-of-5-8-million-americans-finds-that-a-college-degree-yield.html)]
* [College Scorecard Dataset](https://collegescorecard.ed.gov/data)
* [CIP Codes Dataset](https://nces.ed.gov/ipeds/cipcode/resources.aspx?y=55)
* [US News Top 150 Rankings](https://andyreiter.com/datasets/)
* [Distill in RMarkdown](https://rstudio.github.io/distill/)
* ["public institutions generally have lower costs due to government funding"](https://soeonline.american.edu/blog/private-vs-public-institutions/#:~:text=Due%20to%20government%20funding%2C%20public,often%20have%20higher%20tuition%20costs.)
* [Carnegie Classification](https://carnegieclassifications.acenet.edu)
* ["As expected, STEM fields dominate the upper tier"](https://www.insidehighered.com/news/students/careers/2023/05/04/measuring-outcomes-income)
* ["the strong market demand for entry-level STEM jobs, particularly in the engineering and computer science fields"](http://blog.dol.gov/2022/11/04/stem-day-explore-growing-careers)


